#!/usr/bin/env python
import urllib,urllib2,re,sys,os,platform
def ver(l):
	try:
		if not "No such package." in urllib2.urlopen("https://packages.ubuntu.com/trusty/"+l).read():
			print l,"exist."
			return True
		else:
			print l,"doesn't exist."
			return False
	except Exception as e:
		if str(e)=="HTTP Error 404: Not Found":
			print l,"doesn't exist."
			return False
		else:
			print "Error:\n"+str(e)
			sys.exit()
def dl(l):
	page=urllib2.urlopen("https://packages.ubuntu.com/trusty/"+l).read().replace("\n","").replace(" ",";").replace("	",";")
	dls=re.findall('<th><a;href="/trusty/(.*?)</a></th>',page)
	arc=platform.architecture()[0]
	if arc=="64bit":
		arc="amd64"
	elif arc=="32bit":
		arc="i386"
	elif arc=="i386":
		arc="i386"
	elif "arm" in arc:
		arc="arm64"
	else:
		arc="powerpc"
	for d in dls:
		if arc in d:
			dp=urllib2.urlopen("https://packages.ubuntu.com/trusty/"+d.split('">')[0]).read().replace("\n","").replace(" ",";").replace("	",";")
			ld=re.findall('<li><a;href="(.*?).deb">',dp)
			dw=urllib.URLopener()
			dw.retrieve(ld[0]+".deb",(str(ld[0].split("/")[-1:])+".deb").replace("['","").replace("']",""))
			return (str(ld[0].split("/")[-1:])+".deb").replace("['","").replace("']","")
v="0.1.0"
do=""
lib=""
if len(sys.argv)<2:
	while do.lower()!="install" or do.lower()!="remove" or do.lower()!="verify":
		do=raw_input("'install', 'remove' or 'verify': ")
	lib=raw_input("Lib: ")
else:
	if sys.argv[1]=="--help" or sys.argv[1]=="-help" or sys.argv[1]=="-h":
		print "Usage:\nInstall:\ndlib -i lib-name\nor directly:\ndlib lib-name\nRemove:\nwork in progress...\nVerify:\ndlib -ve lib-name\nView version:\ndlib -v"
		sys.exit()
	elif sys.argv[1]=="-v":
		print v
		sys.exit()
	elif sys.argv[1]=="-i":
		do="install"
	elif sys.argv[1]=="-r":
		print "Work in progress for remove..."
		sys.exit()
	elif sys.argv[1]=="-ve":
		do="verify"
	else:
		do="installs"
if do=="installs":
	lib=sys.argv[1:]
	do="install"
else:
	lib=sys.argv[2:]
for l in lib:
	if do=="install":
		print "Verifying "+l+"..."
		if ver(l):
			print "Downloading "+l+"..."
			f=dl(l)
			print "Saved in",f
			if os.path.isfile("/usr/bin/sudo"):
				print "Installing "+f+"..."
				os.system("sudo dpkg -i "+f)
	if do=="remove":
		print "Work in progress..."
		sys.exit()
	if do=="verify":
		ver(l)